### ISSUE TITLE
Invalid string returned by Matches::opt_str

### ISSUE THREAD

**Issue by lucaotta** [rust-lang-nursery/getopts#41]
I've been working on some bugs in uutils and I think I've found a bug in how getopts handles options with dashes and underscores in the name. Check this sample program:

    let args: Vec<String> = env::args().collect();
    let mut opts = Options::new();
    opts.optflag("", "foo_bar", "");
    opts.optopt("", "reference", "", "");

    let matches = match opts.parse(&args[1..]) {
        Ok(m) => m,
        Err(_) => { panic!("Error") }
    };

    matches.opt_present("foo_bar");
    let result = matches.opt_str("reference").and_then(|fname| {
        let mut stat = unsafe { mem::uninitialized() };
        let ret = unsafe { libc::stat(fname.as_ptr() as *const _, &mut stat as *mut libc::stat) };
        if ret == 0 {
            println!("Stat ok");
            Some(fname)
        } else {
            println!("FAIL!");
            None
        }
    });

Launch the program with `touch some_string; ./test --reference some_string`.
I have observed the following:

- if the optional flag is called "foobar", the stat is successful. If it's called "foo_bar" or "foo-bar", the stat always fails;
- moving the `opt_str("reference")` block before the `opt_present` block always works;
- using a `&str` instead of `fname` inside the closure always works;
- inside the `and_then` closure, Rust code executes correctly. Calling libc::stat fails;
- moving the code inside `and_then` into a standalone program works;
- a C program that does a `stat` on the same file works.

This is my first attempt at writing Rust code, so I'm out of ideas on how to debug this further. It seems that `fname.as_ptr()` is somehow invalid in this example.

**Comment by alexcrichton** [comment]
Ah the bug here is that you're passing `&str` to a `libc` call but it needs to be a `CString` or otherwise there's a trailing nul byte missing. Otherwise there's probably some level of corruption happening here, which explains the fishy results!

**Comment by lucaotta** [comment]
Using CString fixed the issue. Thanks for the review!
