### ISSUE TITLE
Update example dependency version

### ISSUE THREAD

**Issue by mcandre** [rust-lang-nursery/getopts#48]
to 0.2.14

**Comment by AlexGustafsson** [comment]
Cargo seems to follow semantic versioning meaning that specifying `0.2` actually means `0.2.x` Therefore there should be no need to update the documentation as `0.2` will result in the latest minor (currently `0.2.18`).

**Comment by KodrAus** [comment]
Thanks @AlexGustafsson. That's right, I think we can close this one, since specifying `0.2` will fetch you the most recent version until our next breaking release.
