### ISSUE TITLE
documentation link is 404

### ISSUE THREAD

**Issue by pornel** [rust-lang-nursery/getopts#54]
https://doc.rust-lang.org/getopts/getopts/index.html

> 404

> File not found

> The site configured at this address does not contain the requested file.

**Comment by steveklabnik** [comment]
Given https://github.com/rust-lang/libc/issues/763 I wonder if this isn't happening with all rust-lang crates.

**Comment by alexcrichton** [comment]
This was likely due to https://github.com/rust-lang/rust/issues/44487 and should get fixed in the near future
