### ISSUE TITLE
Add minimum supported Rust version

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang-nursery/getopts#62]
Currently it's 1.18.

**Comment by KodrAus** [comment]
@RazrFalcon would you like to submit a PR that adds `1.18` to the `.travis.yml` file?

**Comment by RazrFalcon** [comment]
Only travis? What about readme?

**Comment by KodrAus** [comment]
We could put the min version in the readme too. If we did I think we should add a comment to the travis config with a reminder to update the readme too, maybe like:

```yaml
- 1.18.0 # don't forget to update the readme too
```

so they're less likely to get out of sync.
