### ISSUE TITLE
Add #[derive(Debug)] to struct Matches?

### ISSUE THREAD

**Issue by xliiv** [rust-lang-nursery/getopts#64]
Could struct `Matches` have `#[derive(Debug)]`?
I'm not see it [here](https://github.com/rust-lang-nursery/getopts/blob/master/src/lib.rs#L661).

**Comment by KodrAus** [comment]
Good idea! If someone would like to submit a PR that derives `Debug` on `Matches` that would be great :+1:

**Comment by Maxgy** [comment]
Hey, I'll take this up.
