### ISSUE TITLE
Enum Occur requires 1 or more

### ISSUE THREAD

**Issue by xliiv** [rust-lang-nursery/getopts#65]
Change current enum `Occur` to looks like this:
```rust
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Occur {
    /// The option occurs once.
    Req,
    /// The option occurs at most once.
    Optional,
    /// The option occurs zero or more times.
    Multi,
    // NEW PART:
    /// The option occurs 1 or more times
    OneOrMore, // other name?
}
```

**Comment by KodrAus** [comment]
Thanks for the suggestion @xliiv! Unfortunately we can't really update the `Occur` enum without requiring a breaking version bump, so I think this is a bit out-of-scope at this stage. Right now, you can at least set your argument to `Occur::Multi` and use `Matches::opt_count` and check whether it appears at least once.
