### ISSUE TITLE
optflagopt requires `=` form of argument

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/getopts#67]
If you have an `optopt` option (e.g., `--help`) then you can have an argument with either a space or an equals sign (`--help foo` or `--help=foo`). However, `optflagopt` requires the `=` form (`--help=foo` works but `--help foo` is treated the same as `--help`), and this is not documented (and furthermore the help message does not indicate the `=` form is required, it looks like `--help [TOPIC]`, not `--help[=TOPIC]` or `--help=[TOPIC]`).

**Comment by tromey** [comment]
I think the behavior is intentional, see issue #49 for the previous discussion, but the documentation holes are definitely bugs.
