### ISSUE TITLE
Why all tests live in lib.rs

### ISSUE THREAD

**Issue by TisonKun** [rust-lang-nursery/getopts#75]
Could we move them under `tests/`?

**Comment by KodrAus** [comment]
Hi @TisonKun! It's common in Rust for unit tests to live alongside the code they test. These unit tests are different from the tests under the root `/tests` directory, which are integration tests. They don't have access to the library's internals and behave the same as a library that uses `getopts` as a dependency. You can see the tests there pull in `getopts` as an external crate.

Having said that, we could pull the tests out of `lib.rs` to make things easier to follow. Would you like to submit a PR that moves the tests currently under `src/lib.rs` into a `src/tests.rs` or `src/tests/mod.rs` file?

**Comment by TisonKun** [comment]
@KodrAus thanks for your education. That is what I am looking for.

I submit a PR #76 to try to address this issue. But as you see, I am a total newbie to Rust, so any suggestion is helpful and I hope the pull request not that worse :-)
