### ISSUE TITLE
v0.2.20 broke compatibility with older Rust versions

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang-nursery/getopts#90]
Rust 1.18 can build v0.2.19 but not v0.2.21 Does it considered as a braking change?

**Comment by KodrAus** [comment]
Hi @RazrFalcon :wave:

It looks like we're [just targeting the latest stable for `getopts`](https://github.com/rust-lang-nursery/getopts/blob/master/.github/workflows/main.yml#L9) so I don't think we're considering bumps in the minimum supported Rust version as breaking changes.

**Comment by RazrFalcon** [comment]
I see, thanks.

**Comment by commonquail** [comment]
> It looks like we're just targeting the latest stable for getopts

Because 51481592d2ccfb764d2ea769717a2231bfeecbef undid #63 and then 04c6e90faac2675aa89e2176d2eec7d8 pushed MSRV all the way from 1.18 to 1.27, and then 0.2.21 raised it further to 1.31.
